mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demo
    - MYSQL_ROOT_PASSWORD=r$$t
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
  volumes:
    - "/home/wadouk/traning/valtech/isep-devops/mysql-jdbc-vaadin/data:/var/lib/mysql"
    - "/home/wadouk/traning/valtech/isep-devops/mysql-jdbc-vaadin/init-db:/docker-entrypoint-initdb.d"
app:
  image: mysql-jdbc-vaadin
  ports:
    - "666:8080"
  links:
    - mysql:mysql